# Generated by Django 3.2.2 on 2021-08-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='sause',
            field=models.CharField(blank=True, choices=[('rossa', 'rossa'), ('pesto', 'pesto')], max_length=200, null=True),
        ),
    ]
