# Generated by Django 3.2.2 on 2021-08-17 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_dishes_sause'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishes',
            old_name='tags',
            new_name='tag',
        ),
    ]
