# Generated by Django 3.2.2 on 2021-08-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_tags_dishes_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='tag',
        ),
        migrations.AddField(
            model_name='dishes',
            name='tag',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Pizza', 'Pizza'), ('Pasta', 'Pasta'), ('Risotto', 'Risotto'), ('Others', 'Others')], max_length=200, null=True),
        ),
    ]
