# Generated by Django 3.2.2 on 2021-08-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210817_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='pic',
            field=models.ImageField(blank=True, default='images/Quattro.jpg', null=True, upload_to=''),
        ),
    ]
