# Generated by Django 3.2.2 on 2021-08-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210823_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
